kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-edit
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: api-dev
  name: dc90a38f-fcc7-43b1-a8f2-4d7b6bd020d2
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-view
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: web-dev
  name: dc90a38f-fcc7-43b1-a8f2-4d7b6bd020d2
  apiGroup: rbac.authorization.k8s.io