kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-edit
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: web-dev
  name: 963d27bc-88c1-4bb4-98ba-1a2d42d94511
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-view
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: api-dev
  name: 963d27bc-88c1-4bb4-98ba-1a2d42d94511
  apiGroup: rbac.authorization.k8s.io